### Reptiles Index
GET http://localhost:3000/reptiles

### Reptiles Show
GET http://localhost:3000/reptiles/1

### Reptiles Create
POST http://localhost:3000/reptiles
Content-Type: application/json

{
  "com_name": "Eastern Hognose Snake",
  "sci_name": "Heterodon nasicus",
  "classification": "",
  "origin": "North America",
  "conservation_status": "Least Concern"
}

### Reptiles Update
PATCH http://localhost:3000/reptiles/3
Content-Type: application/json

{
  "com_name": "Russian Tortoise",
  "sci_name": "Testudo horsfieldii"
}

### Reptiles Delete
DELETE http://localhost:3000/reptiles/7