@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgxNzAyNzN9.ws6nQFWBW9El52-MKbNVYvoq9JPhpieZv097iAIHM9A

### Reptiles Index
GET http://localhost:3000/reptiles

### Reptiles Show
GET http://localhost:3000/reptiles/1

### Reptiles Create
POST http://localhost:3000/reptiles
Content-Type: application/json

{
  "com_name": "Eastern Hognose Snake",
  "sci_name": "Heterodon nasicus",
  "classification": "",
  "origin": "North America",
  "conservation_status": "Least Concern"
}

### Reptiles Update
PATCH http://localhost:3000/reptiles/3
Content-Type: application/json

{
  "com_name": "Russian Tortoise",
  "sci_name": "Testudo horsfieldii"
}

### Reptiles Delete
DELETE http://localhost:3000/reptiles/7

### Users Index
GET http://localhost:3000/users

### Users Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "Matt",
  "last_name": "Katz",
  "email": "matt@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create (Login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "matt@test.com",
  "password": "password"
}

### Posts Index
GET http://localhost:3000/posts

### Posts Show
GET http://localhost:3000/posts/1

### Posts Create
POST http://localhost:3000/posts
Content-Type: application/json

{
  "caption": "Frogs?",
  "body": "Can I post about frogs?",
  "user_id": "1"
}

### Posts Update
PATCH http://localhost:3000/posts/2
Content-Type: application/json

{
  "body": "Can I post about amphibians?"
}

### Posts Delete
DELETE http://localhost:3000/posts/1